package de.thm.bi.resources;

/**
 * This is a automated generated Class. It is generated by the ResourceManager
 * and lists all Files in a given resources folder.
 * 
 * @author Artur Klos
 * 
 */
public class Resources {
	public static final class Filepaths {
		public static final String MENZEL = "menzel.bmp";
		public static final String H1 = "H 1.bmp";
		public static final String H2 = "H 2.bmp";
		public static final String H3 = "H 3.bmp";
		public static final String PCaG31 = "PCaG3.1.bmp";
		public static final String PCaG32 = "PCaG3.2.bmp";
		public static final String PCaG33 = "PCaG3.3.bmp";
		public static final String PCaG41 = "PCaG4.1.bmp";
		public static final String PCaG42 = "PCaG4.2.bmp";
		public static final String PCaG43 = "PCaG4.3.bmp";
		public static final String PCaG51 = "PCaG5.1.bmp";
		public static final String PCaG52 = "PCaG5.2.bmp";
		public static final String PCaG53 = "PCaG5.3.bmp";
		public static final String RESOURCES_FOLDER = "resources/";
		public static final String test = "test.bmp";
	}
}
